// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParqueoUPDS.Data;

#nullable disable

namespace ParqueoUPDS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121195740_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParqueoUPDS.Models.RegistroParqueo", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistroId"));

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("HorasConsumidas")
                        .HasColumnType("numeric");

                    b.Property<bool>("Recibio_Regalo")
                        .HasColumnType("boolean");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("RegistroId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("RegistroParqueo");
                });

            modelBuilder.Entity("ParqueoUPDS.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculoId"));

                    b.Property<decimal>("HorasAcumuladas")
                        .HasColumnType("numeric");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegalosGanados")
                        .HasColumnType("integer");

                    b.HasKey("VehiculoId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("ParqueoUPDS.Models.RegistroParqueo", b =>
                {
                    b.HasOne("ParqueoUPDS.Models.Vehiculo", "Vehiculo")
                        .WithMany("Registros")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ParqueoUPDS.Models.Vehiculo", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
